name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Project
      run: npm run build
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: dist
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        METHOD: sftp
        PORT: ${{ secrets.FTP_PORT }}
        ARGS: --delete
